services:
  ai-system-analyzer-service:
    build: ./ai-system-analyzer-service
    ports:
      - "5000:5000"

  pq-analyzer-service:
    build: ./pq-analyzer-service
    ports:
      - "5003:5003"

  director-managing-service:
    build: ./director-managing-service
    ports:
      - "5002:5002"
    depends_on:
      - ai-system-analyzer-service
      - pq-analyzer-service

  frontend:
    build: ./frontend
    ports:
      - "5004:80"
    depends_on:
      - director-managing-service
