services:
  unification-generation-service:
    build: ./unification-generation-service
    ports:
      - "5503:5503"

  ai-system-analyzer-service:
    build: ./ai-system-analyzer-service
    ports:
      - "5500:5500"

  pq-analyzer-service:
    build: ./pq-analyzer-service
    ports:
      - "5501:5501"

  director-managing-service:
    build: ./director-managing-service
    ports:
      - "5502:5502"
    depends_on:
      - ai-system-analyzer-service
      - pq-analyzer-service
      - unification-generation-service
    environment:
      - mode=prod

  frontend:
    build: ./frontend
    ports:
      - "5504:80"
    depends_on:
      - director-managing-service
    environment:
      - mode=prod
