logging:
  file.name: ./log/backend.log
  level:
    root: INFO
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    at.ac.tuwien.sepm.groupphase.backend.aspect: DEBUG
  pattern:
    level: r=%X{r} ip=%X{ip} u=%X{u} %5p
  aspect:
    enabled: true
    arg-string-length: 50

server:
  servlet:
    encoding:
      charset: UTF-8
      force: true
  port: 5000

security:
  auth:
    header: Authorization
    prefix: "Bearer "
    login-uri: /api/v1/authentication
  jwt:
    secret: ?E(H+MbQeThWmZq4t7w!z%C*F-J@NcRfUjXn2r5u8x/A?D(G+KbPdSgVkYp3s6v9
    type: JWT
    issuer: secure-backend
    audience: secure-app
    # 12 hours in milliseconds
    expiration-time: 43200000

management:
  server:
    port: 5001
  endpoint:
    shutdown:
      enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - shutdown
          - metrics
          - env
  prometheus:
    metrics:
      export:
        enabled: true

---
spring:
  config:
    activate:
      on-cloud-platform: kubernetes
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  shutdown: graceful
